/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author PC12
 */
public class ViewRentas extends javax.swing.JPanel {

    /**
     * Creates new form ViewRentas
     */
    public ViewRentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtf_id_renta = new javax.swing.JTextField();
        jl_id_cliente = new javax.swing.JLabel();
        jl_costo = new javax.swing.JLabel();
        jb_ultimo = new javax.swing.JButton();
        jb_borrar = new javax.swing.JButton();
        jl_id_pelicula = new javax.swing.JLabel();
        jb_nuevo = new javax.swing.JButton();
        jb_anterior = new javax.swing.JButton();
        jb_agregar = new javax.swing.JButton();
        jl_id_renta = new javax.swing.JLabel();
        jl_formato = new javax.swing.JLabel();
        jtf_id_cliente = new javax.swing.JTextField();
        jb_primero = new javax.swing.JButton();
        jtf_id_pelicula = new javax.swing.JTextField();
        jb_actualizar = new javax.swing.JButton();
        jtf_formato = new javax.swing.JTextField();
        jtf_costo = new javax.swing.JTextField();
        jb_siguiente = new javax.swing.JButton();
        jl_numero_dias = new javax.swing.JLabel();
        jtf_numero_dias = new javax.swing.JTextField();
        jtf_costo_renta = new javax.swing.JTextField();
        jl_costo_renta = new javax.swing.JLabel();

        jl_id_cliente.setText("ID_CLIENTE");

        jl_costo.setText("COSTO");

        jb_ultimo.setText(">|");

        jb_borrar.setText("BORRAR");

        jl_id_pelicula.setText("ID_PELICULA");

        jb_nuevo.setText("NUEVO");

        jb_anterior.setText("<<");
        jb_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_anteriorActionPerformed(evt);
            }
        });

        jb_agregar.setText("AGREGAR");

        jl_id_renta.setText("ID_RENTAS");

        jl_formato.setText("FORMATO");

        jb_primero.setText("|<");

        jtf_id_pelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_id_peliculaActionPerformed(evt);
            }
        });

        jb_actualizar.setText("ACTUALIZAR");

        jtf_formato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_formatoActionPerformed(evt);
            }
        });

        jtf_costo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_costoActionPerformed(evt);
            }
        });

        jb_siguiente.setText(">>");

        jl_numero_dias.setText("NO.DIAS");

        jtf_numero_dias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_numero_diasActionPerformed(evt);
            }
        });

        jtf_costo_renta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_costo_rentaActionPerformed(evt);
            }
        });

        jl_costo_renta.setText("COSTO-RENTA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_costo_renta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_costo_renta, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_numero_dias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_numero_dias, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl_costo)
                            .addComponent(jl_formato)
                            .addComponent(jl_id_pelicula)
                            .addComponent(jl_id_cliente)
                            .addComponent(jl_id_renta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtf_id_renta, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                .addComponent(jtf_id_cliente)
                                .addComponent(jtf_id_pelicula, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jtf_formato, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_costo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 35, Short.MAX_VALUE)
                        .addComponent(jb_primero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_anterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_siguiente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_ultimo)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_agregar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jb_nuevo, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jb_borrar))
                            .addComponent(jb_actualizar))
                        .addGap(8, 8, 8))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_id_renta)
                    .addComponent(jtf_id_renta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_id_cliente)
                            .addComponent(jtf_id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_siguiente)
                            .addComponent(jb_ultimo)
                            .addComponent(jb_anterior)
                            .addComponent(jb_primero))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_id_pelicula)
                            .addComponent(jtf_id_pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_formato)
                            .addComponent(jtf_formato, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_costo)
                            .addComponent(jtf_costo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_numero_dias)
                            .addComponent(jtf_numero_dias, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_costo_renta)
                            .addComponent(jtf_costo_renta, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_agregar)
                            .addComponent(jb_actualizar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_borrar)
                            .addComponent(jb_nuevo))
                        .addGap(110, 110, 110))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jb_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_anteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_anteriorActionPerformed

    private void jtf_id_peliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_id_peliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_id_peliculaActionPerformed

    private void jtf_formatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_formatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_formatoActionPerformed

    private void jtf_costoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_costoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_costoActionPerformed

    private void jtf_numero_diasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_numero_diasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_numero_diasActionPerformed

    private void jtf_costo_rentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_costo_rentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_costo_rentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jb_actualizar;
    public javax.swing.JButton jb_agregar;
    public javax.swing.JButton jb_anterior;
    public javax.swing.JButton jb_borrar;
    public javax.swing.JButton jb_nuevo;
    public javax.swing.JButton jb_primero;
    public javax.swing.JButton jb_siguiente;
    public javax.swing.JButton jb_ultimo;
    public javax.swing.JLabel jl_costo;
    public javax.swing.JLabel jl_costo_renta;
    public javax.swing.JLabel jl_formato;
    public javax.swing.JLabel jl_id_cliente;
    public javax.swing.JLabel jl_id_pelicula;
    public javax.swing.JLabel jl_id_renta;
    public javax.swing.JLabel jl_numero_dias;
    public javax.swing.JTextField jtf_costo;
    public javax.swing.JTextField jtf_costo_renta;
    public javax.swing.JTextField jtf_formato;
    public javax.swing.JTextField jtf_id_cliente;
    public javax.swing.JTextField jtf_id_pelicula;
    public javax.swing.JTextField jtf_id_renta;
    public javax.swing.JTextField jtf_numero_dias;
    // End of variables declaration//GEN-END:variables
}
